export type WorkflowCoverage = {
  unitTests: string[];
  contractTests: string[];
  uiTests: string[];
  e2eTests: string[];
  backendWorkflowTests: string[];
  coreFailurePathTests: string[];
};

export type WorkflowMatrixEntry = {
  id: string;
  workflow: string;
  ownerArea: string;
  entryPoints: string[];
  backendServices: string[];
  expectedOutcome: string;
  happyPath: string;
  keyRejectionPaths: string[];
  roleRules: string[];
  asyncSideEffects: string[];
  notificationSideEffects: string[];
  externalDependencies: string[];
  coverage: WorkflowCoverage;
};

export const workflowMatrix: WorkflowMatrixEntry[] = [
  {
    id: 'auth-account-lifecycle',
    workflow: 'Auth and account lifecycle',
    ownerArea: 'Identity + frontend auth/account',
    entryPoints: [
      'src/pages/SignupPage.tsx',
      'src/pages/AccountPage.tsx',
      'src/contexts/AuthContext.tsx',
      'src/lib/identity-client.ts',
    ],
    backendServices: ['encore/identity/api.ts'],
    expectedOutcome: 'Users can sign up, sign in, verify email, reset password, and manage account profile safely.',
    happyPath: 'Signup -> verify email -> signin -> profile update',
    keyRejectionPaths: ['Invalid token should reject verify/reset actions', 'Suspended/deactivated access is blocked'],
    roleRules: ['Anonymous users cannot access protected routes', 'Only authenticated users update profile'],
    asyncSideEffects: ['Email verification and password reset token issuance'],
    notificationSideEffects: [],
    externalDependencies: ['email delivery provider'],
    coverage: {
      unitTests: ['tests/account-status.test.ts', 'tests/dev-login-env.test.ts'],
      contractTests: ['tests/api-clients.test.ts', 'tests/session-cookie.test.ts'],
      uiTests: ['tests/ui/auth-context.test.tsx'],
      e2eTests: [],
      backendWorkflowTests: [],
      coreFailurePathTests: ['tests/account-status.test.ts', 'tests/dev-login-env.test.ts'],
    },
  },
  {
    id: 'listing-discovery-booking-request',
    workflow: 'Listing discovery and booking request',
    ownerArea: 'Catalog + booking + frontend explore',
    entryPoints: ['src/pages/ExploreView.tsx', 'src/components/ListingDetail.tsx', 'src/lib/platform-client.ts'],
    backendServices: ['encore/catalog/api.ts', 'encore/booking/api.ts'],
    expectedOutcome: 'Guests can discover listings, request stays, and receive the correct initial booking state.',
    happyPath: 'Guest explores -> opens listing -> submits booking request',
    keyRejectionPaths: ['Requested nights overlap blocked availability', 'Invalid booking dates are rejected'],
    roleRules: ['Only authenticated guests can create bookings'],
    asyncSideEffects: ['Booking requested notification for host'],
    notificationSideEffects: ['Host receives enquiry notification'],
    externalDependencies: [],
    coverage: {
      unitTests: ['tests/booking-workflow.test.ts', 'tests/listing-availability-ui.test.ts'],
      contractTests: ['tests/api-clients.test.ts'],
      uiTests: ['tests/ui/guest-dashboard.test.tsx'],
      e2eTests: ['tests/e2e/happy-path.spec.ts'],
      backendWorkflowTests: ['tests/backend-notification-helpers.test.ts'],
      coreFailurePathTests: ['tests/booking-workflow.test.ts', 'tests/listing-availability-ui.test.ts'],
    },
  },
  {
    id: 'booking-enquiry-payment-lifecycle',
    workflow: 'Booking/enquiry/payment lifecycle',
    ownerArea: 'Booking + host/guest workflow UI',
    entryPoints: ['src/pages/HostEnquiries.tsx', 'src/pages/HostDashboard.tsx', 'src/components/PaymentProofDialog.tsx'],
    backendServices: ['encore/booking/api.ts', 'encore/booking/workflow.ts'],
    expectedOutcome: 'Enquiries progress through approval/payment/confirmation with explicit state rules and deadlines.',
    happyPath: 'Host approves -> guest submits proof -> host confirms payment -> booking marked BOOKED',
    keyRejectionPaths: ['Invalid state transitions are rejected', 'Guests cannot mark payment complete directly'],
    roleRules: ['Host-only approval/confirmation actions', 'Guest-only proof submission'],
    asyncSideEffects: ['Inquiry expiry cycle auto-expires stale enquiries'],
    notificationSideEffects: ['Guest approval/payment notifications', 'Host payment-proof notifications'],
    externalDependencies: ['off-platform payment evidence'],
    coverage: {
      unitTests: ['tests/booking-workflow.test.ts', 'tests/inquiry-state.test.ts'],
      contractTests: ['tests/api-clients.test.ts'],
      uiTests: ['tests/ui/host-dashboard.test.tsx', 'tests/ui/guest-dashboard.test.tsx'],
      e2eTests: ['tests/e2e/happy-path.spec.ts'],
      backendWorkflowTests: ['tests/backend-notification-helpers.test.ts'],
      coreFailurePathTests: ['tests/booking-workflow.test.ts', 'tests/inquiry-state.test.ts'],
    },
  },
  {
    id: 'host-availability-management',
    workflow: 'Host availability management',
    ownerArea: 'Catalog availability + host calendar UI',
    entryPoints: ['src/pages/HostAvailability.tsx', 'src/lib/host-availability.ts'],
    backendServices: ['encore/catalog/api.ts', 'encore/catalog/availability.ts'],
    expectedOutcome: 'Hosts can manage manual blocks without violating approved/booked lock rules.',
    happyPath: 'Host blocks/unblocks ranges and sees server summary updates',
    keyRejectionPaths: ['Locked approved/booked dates cannot be manually changed'],
    roleRules: ['Only listing owners update host availability'],
    asyncSideEffects: ['Availability summary reflects booking-driven constraints'],
    notificationSideEffects: [],
    externalDependencies: [],
    coverage: {
      unitTests: ['tests/host-availability.test.ts', 'tests/catalog-availability.test.ts'],
      contractTests: ['tests/api-clients.test.ts'],
      uiTests: [],
      e2eTests: [],
      backendWorkflowTests: [],
      coreFailurePathTests: ['tests/host-availability.test.ts', 'tests/catalog-availability.test.ts'],
    },
  },
  {
    id: 'listing-create-edit-quota-media',
    workflow: 'Listing create/edit with quota and media entitlements',
    ownerArea: 'Catalog + billing plan restrictions + host listing UI',
    entryPoints: ['src/pages/CreateListing.tsx', 'src/lib/platform-client.ts'],
    backendServices: ['encore/catalog/api.ts', 'encore/catalog/quota.ts', 'encore/billing/api.ts'],
    expectedOutcome: 'Hosts can create/edit listings within plan limits and upload permitted media.',
    happyPath: 'Host creates or edits listing with allowed media set for plan tier',
    keyRejectionPaths: ['Standard hosts blocked from video upload', 'Quota enforcement blocks over-limit listing creation'],
    roleRules: ['Host role required for listing management'],
    asyncSideEffects: ['Signed upload URL generation for media'],
    notificationSideEffects: ['Listing moderation notifications'],
    externalDependencies: ['object storage signed uploads'],
    coverage: {
      unitTests: ['tests/catalog-billing-helpers.test.ts'],
      contractTests: ['tests/api-clients.test.ts'],
      uiTests: ['tests/ui/create-listing.test.tsx'],
      e2eTests: [],
      backendWorkflowTests: ['tests/backend-notification-helpers.test.ts'],
      coreFailurePathTests: ['tests/catalog-billing-helpers.test.ts', 'tests/ui/create-listing.test.tsx'],
    },
  },
  {
    id: 'kyc-submission-review',
    workflow: 'KYC submission and admin review',
    ownerArea: 'Ops + identity + account/admin UI',
    entryPoints: ['src/components/KYCModal.tsx', 'src/pages/AccountPage.tsx', 'src/pages/AdminDashboard.tsx', 'src/lib/ops-client.ts'],
    backendServices: ['encore/ops/api.ts', 'encore/identity/api.ts'],
    expectedOutcome: 'Hosts submit KYC and admins can approve/reject with auditable status changes.',
    happyPath: 'Host submits KYC -> admin reviews -> host sees resulting status',
    keyRejectionPaths: ['Invalid/inaccessible KYC assets fail review path safely'],
    roleRules: ['Only admin can review KYC submissions'],
    asyncSideEffects: ['Audit log entries'],
    notificationSideEffects: ['KYC reviewed notifications'],
    externalDependencies: ['secure bucket storage'],
    coverage: {
      unitTests: ['tests/backend-notification-helpers.test.ts'],
      contractTests: ['tests/api-clients.test.ts'],
      uiTests: ['tests/ui/admin-dashboard-data.test.tsx'],
      e2eTests: [],
      backendWorkflowTests: [],
      coreFailurePathTests: ['tests/api-clients.test.ts'],
    },
  },
  {
    id: 'subscriptions-host-billing',
    workflow: 'Subscription checkout and host billing lifecycle',
    ownerArea: 'Billing + pricing UI',
    entryPoints: ['src/pages/PricingPage.tsx', 'src/lib/billing-client.ts'],
    backendServices: ['encore/billing/api.ts', 'encore/billing/host-billing.ts', 'encore/billing/webhook-classification.ts'],
    expectedOutcome: 'Plan upgrades, vouchers, card state, and billing status transitions stay consistent and enforceable.',
    happyPath: 'Host starts checkout -> payment succeeds -> entitlement updates',
    keyRejectionPaths: ['Failed/cancelled payments keep plan unchanged', 'Greylisted status restricts host operations'],
    roleRules: ['Billing mutations require authenticated host'],
    asyncSideEffects: ['Webhook classification and host reminder cycle'],
    notificationSideEffects: ['Subscription activated/payment failure notifications'],
    externalDependencies: ['payment provider webhook'],
    coverage: {
      unitTests: ['tests/host-billing-lifecycle.test.ts', 'tests/host-billing-ui.test.ts', 'tests/catalog-billing-helpers.test.ts'],
      contractTests: ['tests/api-clients.test.ts'],
      uiTests: [],
      e2eTests: [],
      backendWorkflowTests: ['tests/backend-notification-helpers.test.ts'],
      coreFailurePathTests: ['tests/host-billing-lifecycle.test.ts', 'tests/catalog-billing-helpers.test.ts'],
    },
  },
  {
    id: 'content-studio-lifecycle',
    workflow: 'Content Studio draft generation and publication lifecycle',
    ownerArea: 'Billing content engine + host social UI',
    entryPoints: ['src/pages/SocialDashboard.tsx', 'src/lib/billing-client.ts', 'src/lib/ai-client.ts'],
    backendServices: ['encore/billing/api.ts'],
    expectedOutcome: 'Hosts can generate, edit, schedule, and publish content drafts with entitlement limits.',
    happyPath: 'Generate draft -> save/schedule -> publish status update',
    keyRejectionPaths: ['Insufficient entitlements prevent generation', 'Invalid scheduled dates are rejected'],
    roleRules: ['Host-only access to content studio'],
    asyncSideEffects: ['Checkout callback updates content credit balances'],
    notificationSideEffects: ['Content credits purchased notifications'],
    externalDependencies: ['AI text/media generation'],
    coverage: {
      unitTests: ['tests/social-template-engine.test.ts', 'tests/text-generation.test.ts'],
      contractTests: ['tests/api-clients.test.ts'],
      uiTests: [],
      e2eTests: [],
      backendWorkflowTests: ['tests/backend-notification-helpers.test.ts'],
      coreFailurePathTests: ['tests/text-generation.test.ts', 'tests/ai-rails.test.ts'],
    },
  },
  {
    id: 'messaging-attachments',
    workflow: 'Messaging and attachment upload',
    ownerArea: 'Messaging service + chat UI',
    entryPoints: ['src/components/ChatModal.tsx', 'src/lib/messaging-client.ts'],
    backendServices: ['encore/messaging/api.ts'],
    expectedOutcome: 'Guests and hosts exchange messages with safe attachment upload flows.',
    happyPath: 'User opens chat -> sends message -> recipient can read',
    keyRejectionPaths: ['Unauthorized booking chat access denied'],
    roleRules: ['Only booking participants can message on a booking thread'],
    asyncSideEffects: ['Message timestamps and delivery state updates'],
    notificationSideEffects: ['Message received notifications'],
    externalDependencies: ['attachment object storage'],
    coverage: {
      unitTests: ['tests/backend-notification-helpers.test.ts'],
      contractTests: ['tests/api-clients.test.ts'],
      uiTests: [],
      e2eTests: [],
      backendWorkflowTests: [],
      coreFailurePathTests: ['tests/api-clients.test.ts'],
    },
  },
  {
    id: 'reviews-lifecycle',
    workflow: 'Review creation and moderation lifecycle',
    ownerArea: 'Reviews + guest/admin UI',
    entryPoints: ['src/components/ReviewForm.tsx', 'src/pages/AdminDashboard.tsx', 'src/lib/platform-client.ts'],
    backendServices: ['encore/reviews/api.ts'],
    expectedOutcome: 'Guests can review stays and admins can moderate review status/deletion.',
    happyPath: 'Booked guest posts review -> review appears on listing',
    keyRejectionPaths: ['Duplicate/invalid review submissions are rejected'],
    roleRules: ['Only eligible guests create reviews', 'Admin-only moderation controls'],
    asyncSideEffects: ['Review aggregates recompute for listing'],
    notificationSideEffects: ['Listing reviewed notifications'],
    externalDependencies: [],
    coverage: {
      unitTests: [],
      contractTests: ['tests/api-clients.test.ts'],
      uiTests: ['tests/ui/admin-dashboard-data.test.tsx'],
      e2eTests: [],
      backendWorkflowTests: ['tests/backend-notification-helpers.test.ts'],
      coreFailurePathTests: ['tests/api-clients.test.ts'],
    },
  },
  {
    id: 'notifications-lifecycle',
    workflow: 'Notifications lifecycle',
    ownerArea: 'Ops notifications + notification context UI',
    entryPoints: ['src/components/NotificationBell.tsx', 'src/context/NotificationContext.tsx', 'src/lib/notification-client.ts'],
    backendServices: ['encore/ops/api.ts', 'encore/ops/notification-builders.ts'],
    expectedOutcome: 'Users can receive, read, and dismiss actionable notifications without state drift.',
    happyPath: 'Notification appears -> user reads/dismisses -> state persists',
    keyRejectionPaths: ['Unauthorized notification mutation is rejected'],
    roleRules: ['Users mutate only their own inbox state'],
    asyncSideEffects: ['Read-all operations timestamp all active notifications'],
    notificationSideEffects: ['All workflow domains can publish notifications here'],
    externalDependencies: [],
    coverage: {
      unitTests: ['tests/backend-notification-helpers.test.ts'],
      contractTests: ['tests/api-clients.test.ts'],
      uiTests: ['tests/ui/notification-context.test.tsx'],
      e2eTests: ['tests/e2e/happy-path.spec.ts'],
      backendWorkflowTests: [],
      coreFailurePathTests: ['tests/api-clients.test.ts', 'tests/ui/notification-context.test.tsx'],
    },
  },
  {
    id: 'referrals-leaderboard',
    workflow: 'Referrals and leaderboard',
    ownerArea: 'Referrals + identity leaderboard + referral UI',
    entryPoints: ['src/pages/ReferralView.tsx', 'src/lib/identity-client.ts', 'src/lib/platform-client.ts'],
    backendServices: ['encore/referrals/api.ts', 'encore/identity/api.ts'],
    expectedOutcome: 'Users share referral codes and see reward progression and leaderboard data.',
    happyPath: 'Referral tracked -> reward computed -> user sees progress and leaderboard',
    keyRejectionPaths: ['Rejected rewards remain rejected and do not silently map to pending'],
    roleRules: ['Rewards scoped to current user unless admin'],
    asyncSideEffects: ['Reward creation is idempotent for paid triggers'],
    notificationSideEffects: ['Referral reward earned notifications'],
    externalDependencies: [],
    coverage: {
      unitTests: ['tests/backend-notification-helpers.test.ts'],
      contractTests: ['tests/api-clients.test.ts'],
      uiTests: [],
      e2eTests: [],
      backendWorkflowTests: [],
      coreFailurePathTests: ['tests/api-clients.test.ts'],
    },
  },
  {
    id: 'admin-moderation-settings',
    workflow: 'Admin moderation and platform settings',
    ownerArea: 'Admin frontend + ops/identity/reviews/referrals services',
    entryPoints: ['src/pages/AdminDashboard.tsx', 'src/features/admin/use-admin-dashboard-data.ts', 'src/lib/admin-client.ts'],
    backendServices: ['encore/ops/api.ts', 'encore/identity/api.ts', 'encore/reviews/api.ts', 'encore/referrals/api.ts', 'encore/catalog/api.ts'],
    expectedOutcome: 'Admins can moderate users/listings/reviews/referrals and manage settings with auditability.',
    happyPath: 'Admin loads dashboard -> updates moderation state -> derived stats refresh',
    keyRejectionPaths: ['Unauthorized users cannot access admin actions'],
    roleRules: ['Admin role required for all moderation endpoints'],
    asyncSideEffects: ['Audit logs + moderation notifications'],
    notificationSideEffects: ['User-facing moderation notifications'],
    externalDependencies: [],
    coverage: {
      unitTests: [],
      contractTests: ['tests/api-clients.test.ts'],
      uiTests: ['tests/ui/admin-dashboard-data.test.tsx'],
      e2eTests: [],
      backendWorkflowTests: [],
      coreFailurePathTests: ['tests/api-clients.test.ts'],
    },
  },
  {
    id: 'trip-planner-ai',
    workflow: 'Trip planner and AI-assisted flows',
    ownerArea: 'AI endpoints + planner UI',
    entryPoints: ['src/pages/HolidayPlanner.tsx', 'src/lib/ai-client.ts', 'src/services/content.ts'],
    backendServices: ['server.ts AI proxy endpoints'],
    expectedOutcome: 'Users receive constrained AI planning/content responses with guardrails and rate limiting.',
    happyPath: 'User sends trip prompt -> receives generated response',
    keyRejectionPaths: ['Rate-limited and invalid payloads fail with explicit errors'],
    roleRules: ['AI endpoints enforce input validation and abuse limits'],
    asyncSideEffects: ['Rate-limit windows track per client key/IP'],
    notificationSideEffects: [],
    externalDependencies: ['AI providers'],
    coverage: {
      unitTests: ['tests/ai-client.test.ts', 'tests/ai-rails.test.ts', 'tests/text-generation.test.ts'],
      contractTests: [],
      uiTests: [],
      e2eTests: [],
      backendWorkflowTests: [],
      coreFailurePathTests: ['tests/ai-rails.test.ts', 'tests/text-generation.test.ts'],
    },
  },
];
